### ISSUE TITLE
Need of Web UI for Greenmail to retrieve sent emails

### ISSUE THREAD

**Issue by mohitdguptattn** [greenmail-mail-test/greenmail#164]
Hi,

I am currently working on Greenmail to send and retrieve emails for different environments of my application. I have set up the Greenmail server using docker container and it is correctly working. I am also able to send mails using SMTP to different email addresses. I have explored out but didnt find any good Web UI to check my emails. I have also tried integrating Roundcube with Greenmail but it started giving exception like "**No enum constant com.icegreen.greenmail.imap.commands.SearchKey**."
Kindly help.

**Comment by marcelmay** [comment]
Hi @mohitdguptattn ,

- which GreenMail version do you use
- can you provide a more detailed error message from GreenMail log, as to which specific IMAP search fails

Currently there is no Web UI, and personally I use Thunderbird or Mail.app clients.
PHP based WebUIs like SquirrelMail ( #2 ) have some issues due to not all imap search fully implemented yet ( #20 ).

FYI, there is a [GreenMail Docker](http://www.icegreen.com/greenmail/#deploy_docker_standalone) image.

**Comment by mohitdguptattn** [comment]
Hi @marcelmay 

We are using greenmail 1.5.2. For retrieving the emails we are trying the JBOSS JMX console as suggested in the document at www.icegreen.com/greenmail . 


However we are facing the following logs:

No enum constant com.icegreen.greenmail.imap.commands.SearchKey.1
	at java.lang.Enum.valueOf(Enum.java:236)
	at com.icegreen.greenmail.imap.commands.SearchKey.valueOf(SearchKey.java:67)
	at com.icegreen.greenmail.imap.commands.SearchCommandParser.searchTerm(SearchCommandParser.java:68)
	at com.icegreen.greenmail.imap.commands.SearchCommand.doProcess(SearchCommand.java:53)
	at com.icegreen.greenmail.imap.commands.UidCommand.doProcess(UidCommand.java:42)
	at com.icegreen.greenmail.imap.commands.CommandTemplate.process(CommandTemplate.java:57)
	at com.icegreen.greenmail.imap.ImapRequestHandler.doProcessRequest(ImapRequestHandler.java:98)
	at com.icegreen.greenmail.imap.ImapRequestHandler.handleRequest(ImapRequestHandler.java:51)
	at com.icegreen.greenmail.imap.ImapHandler.run(ImapHandler.java:69)
	at com.icegreen.greenmail.server.AbstractServer$1.run(AbstractServer.java:163)
	at java.lang.Thread.run(Thread.java:745)

**Comment by marcelmay** [comment]
Can you get the debug output from GreenMail?

There will be the exact IMAP search command included, so we can see which search was executed. Otherwise, I'll setup roundcube and try to reproduce the issue.

**Comment by gusran** [comment]
We were able to set-up Rainloop togheter with GrenMail, and besides the [issue](https://github.com/greenmail-mail-test/greenmail/issues/172) with text/html it works well (we made a quick fix for that problem in GreenMail).

**Comment by marcelmay** [comment]
@mohitdguptattn :  #174 fixed this search issue.

I tested Rainloop / 1.10.5.192 with latest GreenMail [1.6.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/icegreen).
