### ISSUE TITLE
Support searching by message sequence

### ISSUE THREAD

**Issue by rjfioravanti** [greenmail-mail-test/greenmail#174]
I am interested in the commands:
UID SEARCH 1:100
SEARCH 1:100

From https://tools.ietf.org/html/rfc3501#section-6.4.4, "sequence set" is a possible search key, that seems was not accounted for in https://github.com/greenmail-mail-test/greenmail/issues/103 or https://github.com/greenmail-mail-test/greenmail/issues/20

      <sequence set>
         Messages with message sequence numbers corresponding to the
         specified message sequence number set.

Sequence set can be various things, a single number, a from:to, or comma separated numbers, e.g. 1,2,3

**Comment by rjfioravanti** [comment]
This is the logs leading up to the error, and the resulting stacktrace

Jan 03, 2017 12:23:28 PM com.icegreen.greenmail.imap.commands.SearchCommandParser searchTerm
WARNING: Ignoring not yet implemented search command '1:1'
java.lang.IllegalArgumentException: No enum constant com.icegreen.greenmail.imap.commands.SearchKey.1:1
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.icegreen.greenmail.imap.commands.SearchKey.valueOf(SearchKey.java:67)
        at com.icegreen.greenmail.imap.commands.SearchCommandParser.searchTerm(SearchCommandParser.java:68)
        at com.icegreen.greenmail.imap.commands.SearchCommand.doProcess(SearchCommand.java:53)
        at com.icegreen.greenmail.imap.commands.UidCommand.doProcess(UidCommand.java:42)
        at com.icegreen.greenmail.imap.commands.CommandTemplate.process(CommandTemplate.java:57)
        at com.icegreen.greenmail.imap.ImapRequestHandler.doProcessRequest(ImapRequestHandler.java:98)
        at com.icegreen.greenmail.imap.ImapRequestHandler.handleRequest(ImapRequestHandler.java:51)
        at com.icegreen.greenmail.imap.ImapHandler.run(ImapHandler.java:69)

**Comment by marcelmay** [comment]
@rjfioravanti , I just implemented the search and uploaded a new [1.6.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/icegreen/).

**Comment by technotronic12** [comment]
@marcelmay can you show me an example of how to search by sequence set? I want to write a test for it

**Comment by marcelmay** [comment]
Hi @technotronic12,

there is a [ImapProtocolTest#testSearchSequenceSet](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/test/java/com/icegreen/greenmail/imap/commands/ImapProtocolTest.java#L165)
and [ImapProtocolTest#testUidSearchSequenceSet](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/test/java/com/icegreen/greenmail/imap/commands/ImapProtocolTest.java#L218).
