### ISSUE TITLE
Forwarding an attached message RFC822 message causes NPE

### ISSUE THREAD

**Issue by marcelmay** [greenmail-mail-test/greenmail#178]
When forwarding a multipart/alternative message GreenMail throws a NPE as no SENT DATE exists.

1687597 DEBUG map.ImapRequestLineReader| IMAP Line received : <TAG4 APPEND "Sent" (\Seen) {1659}\r\n\r\n>
1687599 ERROR e.SimpleMessageAttributes| message type : multipart/alternative;
 boundary="--=_RainLoop_162_327671855.1483897476"
1687601 DEBUG e.SimpleMessageAttributes| Can not recurse through multipart content
java.lang.NullPointerException
	at java.util.Calendar.setTime(Calendar.java:1106)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:955)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:948)
	at javax.mail.internet.MailDateFormat.format(MailDateFormat.java:219)
	at java.text.DateFormat.format(DateFormat.java:336)
	at com.icegreen.greenmail.store.SimpleMessageAttributes.<init>(SimpleMessageAttributes.java:85)
	at com.icegreen.greenmail.store.SimpleMessageAttributes.parseMimePart(SimpleMessageAttributes.java:240)
	at com.icegreen.greenmail.store.SimpleMessageAttributes.<init>(SimpleMessageAttributes.java:88)
	at com.icegreen.greenmail.store.SimpleMessageAttributes.parseMimePart(SimpleMessageAttributes.java:257)
	at com.icegreen.greenmail.store.SimpleMessageAttributes.parseMimePart(SimpleMessageAttributes.java:241)
	at com.icegreen.greenmail.store.SimpleMessageAttributes.<init>(SimpleMessageAttributes.java:88)
	at com.icegreen.greenmail.store.StoredMessage.<init>(StoredMessage.java:64)
	at com.icegreen.greenmail.store.HierarchicalFolder.appendMessage(HierarchicalFolder.java:213)
	at com.icegreen.greenmail.imap.commands.AppendCommand.doProcess(AppendCommand.java:66)
	at com.icegreen.greenmail.imap.commands.CommandTemplate.process(CommandTemplate.java:57)
	at com.icegreen.greenmail.imap.ImapRequestHandler.doProcessRequest(ImapRequestHandler.java:98)
	at com.icegreen.greenmail.imap.ImapRequestHandler.handleRequest(ImapRequestHandler.java:51)
	at com.icegreen.greenmail.imap.ImapHandler.run(ImapHandler.java:71)
	at com.icegreen.greenmail.server.AbstractServer$1.run(AbstractServer.java:163)
	at java.lang.Thread.run(Thread.java:745)

**Comment by marcelmay** [comment]
Relates to #142
