### ISSUE TITLE
Question - javax.net.ssl.SSLException while using IMAPS

### ISSUE THREAD

**Issue by bhupendraM** [greenmail-mail-test/greenmail#203]
Hi,
I have deployed Greenmail as war in tomcat. 
Configured greenmail.imaps.host/port in web.xml
When I am trying to configure an account using outlook, I am not able to do so and on tomcat console I get following exception, and the configuration fails.

Am I missing anything on the configuration end for SSL ?

[smtps:192.168.xxx.xxx:3465<-/192.1xx.162.xxx:62675] ERROR com.icegreen.greenmail.smtp.SmtpHandler - Unexpected error handling connection, quitting=
javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1476)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:92)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:154)
        at java.io.BufferedReader.readLine(BufferedReader.java:317)
        at java.io.BufferedReader.readLine(BufferedReader.java:382)
        at com.icegreen.greenmail.smtp.SmtpConnection.receiveLine(SmtpConnection.java:57)
        at com.icegreen.greenmail.smtp.SmtpHandler.handleCommand(SmtpHandler.java:82)
        at com.icegreen.greenmail.smtp.SmtpHandler.run(SmtpHandler.java:56)
        at com.icegreen.greenmail.server.AbstractServer$1.run(AbstractServer.java:163)
        at java.lang.Thread.run(Thread.java:722)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:946)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:702)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.PrintWriter.flush(PrintWriter.java:320)
        at com.icegreen.greenmail.util.InternetPrintWriter.println(InternetPrintWriter.java:91)
        at com.icegreen.greenmail.util.InternetPrintWriter.println(InternetPrintWriter.java:196)
        at com.icegreen.greenmail.smtp.SmtpConnection.send(SmtpConnection.java:48)
        at com.icegreen.greenmail.smtp.SmtpHandler.sendGreetings(SmtpHandler.java:76)
        at com.icegreen.greenmail.smtp.SmtpHandler.run(SmtpHandler.java:53)
        ... 2 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(InputRecord.java:482)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:927)

**Comment by bhupendraM** [comment]
Further to this, openSSL shows that certificate is expired.. not sure if the error is due to above?

If yes, how do I get/update the valid certificate ?


CONNECTED(000001B0)
depth=0 C = US, O = Icegreen Technologies, OU = GreenMail, CN = GreenMail selfsigned Test Certificate
verify error:num=18:self signed certificate
verify return:1
depth=0 C = US, O = Icegreen Technologies, OU = GreenMail, CN = GreenMail selfsigned Test Certificate
verify error:num=10:certificate has expired
notAfter=Jan 10 07:22:27 2013 GMT
verify return:1
depth=0 C = US, O = Icegreen Technologies, OU = GreenMail, CN = GreenMail selfsigned Test Certificate
notAfter=Jan 10 07:22:27 2013 GMT
verify return:1
11168:error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small:.\ssl\s3_clnt.c:3635:
---
Certificate chain
 0 s:/C=US/O=Icegreen Technologies/OU=GreenMail/CN=GreenMail selfsigned Test Certificate
   i:/C=US/O=Icegreen Technologies/OU=GreenMail/CN=GreenMail selfsigned Test Certificate
-----BEGIN CERTIFICATE-----
MIIDHTCCAtqgAwIBAgIES0rRszALBgcqhkjOOAQDBQAwcTELMAkGA1UEBhMCVVMx
HjAcBgNVBAoTFUljZWdyZWVuIFRlY2hub2xvZ2llczESMBAGA1UECxMJR3JlZW5N
YWlsMS4wLAYDVQQDEyVHcmVlbk1haWwgc2VsZnNpZ25lZCBUZXN0IENlcnRpZmlj
YXRlMB4XDTEwMDExMTA3MjIyN1oXDTEzMDExMDA3MjIyN1owcTELMAkGA1UEBhMC
VVMxHjAcBgNVBAoTFUljZWdyZWVuIFRlY2hub2xvZ2llczESMBAGA1UECxMJR3Jl
ZW5NYWlsMS4wLAYDVQQDEyVHcmVlbk1haWwgc2VsZnNpZ25lZCBUZXN0IENlcnRp
ZmljYXRlMIIBuDCCASwGByqGSM44BAEwggEfAoGBAP1/U4EddRIpUt9KnC7s5Of2
EbdSPO9EAMMeP4C2USZpRV1AIlH7WT2NWPq/xfW6MPbLm1Vs14E7gB00b/JmYLdr
mVClpJ+f6AR7ECLCT7up1/63xhv4O1fnxqimFQ8E+4P208UewwI1VBNaFpEy9nXz
rith1yrv8iIDGZ3RSAHHAhUAl2BQjxUjC8yykrmCouuEC/BYHPUCgYEA9+Gghdab
Pd7LvKtcNrhXuXmUr7v6OuqC+VdMCz0HgmdRWVeOutRZT+ZxBxCBgLRJFnEj6Ewo
FhO3zwkyjMim4TwWeotUfI0o4KOuHiuzpnWRbqN/C/ohNWLx+2J6ASQ7zKTxvqhR
kImog9/hWuWfBpKLZl6Ae1UlZAFMO/7PSSoDgYUAAoGBAMJ+USMYwapPbHt1LHEd
k5j3ZWp34TI3hxBD4u6rZDTcKORtvgB9ptlKOKzqFyUpXg8goVmEByDXFQPw0LKr
zd1EBip1KSBjxM2djIS+a0nRzpkUotRZ+M1N0sNIroJhXGcYztR85/UktPTibxmu
dwBS6fJf46iQ0ciKR4GWbXkpMAsGByqGSM44BAMFAAMwADAtAhRnkE7LeByc/jRp
G/UWQoc8RJPP3wIVAI7EYSiqf4XXyTiJr9RZKLBLjbAD
-----END CERTIFICATE-----
---
Server certificate
subject=/C=US/O=Icegreen Technologies/OU=GreenMail/CN=GreenMail selfsigned Test Certificate
issuer=/C=US/O=Icegreen Technologies/OU=GreenMail/CN=GreenMail selfsigned Test Certificate
---
No client certificate CA names sent
Peer signing digest: SHA1
Server Temp Key: DH, 768 bits
---
SSL handshake has read 1249 bytes and written 7 bytes
---
New, (NONE), Cipher is (NONE)
Server public key is 1024 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 591C46C7A2524C61F03D8464659EF9FC874727F0BD7A15E675B6D7296D7398A8
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1495025201
    Timeout   : 300 (sec)
    Verify return code: 10 (certificate has expired)

**Comment by marcelmay** [comment]
You can add an alternate certificate to the classpath. See [DummySSLServerSocketFactory.java](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/main/java/com/icegreen/greenmail/util/DummySSLServerSocketFactory.java#L26).

**Comment by marcelmay** [comment]
I added an issue for updating the embedded certificate : #206

**Comment by marcelmay** [comment]
Related with #199

**Comment by buildscientist** [comment]
Related to #130 - in that if we allow dynamic import of a JKS - users can generate their own certificates for use within the keystore.

**Comment by chriswhite199** [comment]
With the cert being updated in #206, is this issue still valid? (i'm pushing to get 1.5.6 published if you hadn't guessed)

**Comment by marcelmay** [comment]
Just checked with Thunderbird 52.2.1 :
Sending via SMTPS and receiving via IMAPS works with current development version (after confirming in Thunderbird to accept certificate from unknown_ca).
