### ISSUE TITLE
GreenMail Standalone Docker runs into JDK 7 SSL issue with latest  openjdk:7-jre-alpine base image

### ISSUE THREAD

**Issue by marcelmay** [greenmail-mail-test/greenmail#221]
Building with latest Docker base image openjdk:7-jre-alpine fails due to broken JDK version:

```
Exception in thread "smtps:0.0.0.0:3465<-/172.17.0.1:33220" java.lang.ExceptionInInitializerError
	at sun.security.ssl.HelloExtensions.<init>(HelloExtensions.java:85)
	at sun.security.ssl.HandshakeMessage$ClientHello.<init>(HandshakeMessage.java:240)
	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:219)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:961)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:897)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1033)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1342)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:719)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at java.io.PrintWriter.flush(PrintWriter.java:320)
	at com.icegreen.greenmail.util.InternetPrintWriter.println(InternetPrintWriter.java:91)
	at com.icegreen.greenmail.util.InternetPrintWriter.println(InternetPrintWriter.java:196)
	at com.icegreen.greenmail.smtp.SmtpConnection.send(SmtpConnection.java:46)
	at com.icegreen.greenmail.smtp.SmtpHandler.sendGreetings(SmtpHandler.java:76)
	at com.icegreen.greenmail.smtp.SmtpHandler.run(SmtpHandler.java:53)
	at com.icegreen.greenmail.server.AbstractServer$1.run(AbstractServer.java:154)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: System property jdk.tls.namedGroups(null) contains no supported elliptic curves
	at sun.security.ssl.SupportedEllipticCurvesExtension.<clinit>(SupportedEllipticCurvesExtension.java:154)
	... 22 more
```
This is related to https://bugs.openjdk.java.net/browse/JDK-8173783 and latest alpine using JDK 1.7.0_131 .

Workaround is to pin to base image with previous JDK version using openjdk:7u121-jre-alpine .

**Comment by marcelmay** [comment]
Link to relevant [Docker JDK base image issue](https://github.com/docker-library/openjdk/issues/117)
