### ISSUE TITLE
Concurrency issues when creating/deleting users

### ISSUE THREAD

**Issue by 1livv** [greenmail-mail-test/greenmail#245]
Hi,

Context: I have a few hundred tests that rely on greenmail. The tests are run in parallel to decrease the run time. A typical test will:

- Create an user
- Call an external service to send a mail to the newly created user
- Wait for that email and check it's content
- Delete the user

The problem is that sometimes I run into concurrency issues, specifically:                      
       `Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.icegreen.greenmail.store.InMemoryStore$HierarchicalFolder.getChild(InMemoryStore.java:320)
	at com.icegreen.greenmail.store.InMemoryStore.getMailbox(InMemoryStore.java:53)
	at com.icegreen.greenmail.imap.ImapHostManagerImpl.getFolder(ImapHostManagerImpl.java:63)
	at com.icegreen.greenmail.imap.ImapHostManagerImpl.getInbox(ImapHostManag`

One of the causes seems to be an unprotected field in HierarchicalFolder class                 
> private Collection<HierarchicalFolder> children

For now I'm using the 1.4.1 version. I tried upgrading to the latest version but the problem persists

**Comment by marcelmay** [comment]
@1livv , can you provide a simple test case for reproducing this?

**Comment by 1livv** [comment]
Hi @marcelmay 
I made a repo to reproduce this issue.
Could you take a look?

https://github.com/1livv/greenmail-test
