### ISSUE TITLE
ConcurrentModificationException in getAllMessages

### ISSUE THREAD

**Issue by michaelzangl** [greenmail-mail-test/greenmail#271]
Occurred while getting the mail in one thread and the background server was still sending more mails.

```
org.opentest4j.AssertionFailedError
        ....
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1045)
	at com.icegreen.greenmail.store.InMemoryStore.listMailboxes(InMemoryStore.java:168)
	at com.icegreen.greenmail.imap.ImapHostManagerImpl.getAllMessages(ImapHostManagerImpl.java:44)
	at com.icegreen.greenmail.util.GreenMail.getReceivedMessages(GreenMail.java:219)
        ...
```

**Comment by marcelmay** [comment]
Thx alot, @michaelzangl .

Which are you using?

**Comment by michaelzangl** [comment]
com.icegreen:greenmail:1.5.9

**Comment by marcelmay** [comment]
It is difficult to reproduce the error, but it should be fixed by the switch to CopyOnWriteArrayList.

 I'll create a new release this week.
