### ISSUE TITLE
SearchCommandParser doesn't parse a header command properly

### ISSUE THREAD

**Issue by Impakt** [greenmail-mail-test/greenmail#333]
Im writing some test cases that uses greenmail as the server and jodd as the client. When using IMAP to try and read and then delete an email i get the following (truncated):

```
A11 SEARCH (HEADER Message-ID <1627010197.0.1593681191102@[192.168.242.10]> SEEN) ALL
```

which results in the following exceptions
```
2020-07-02 19:26:54,165 WARN  [imap:127.0.0.1:1102<-/127.0.0.1:49855] commands.SearchCommandParser (SearchCommandParser.java:118) - Ignoring not yet implemented search command '(HEADER'


java.lang.IllegalArgumentException: No enum constant com.icegreen.greenmail.imap.commands.SearchKey.(HEADER
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_242]
	at com.icegreen.greenmail.imap.commands.SearchKey.valueOf(SearchKey.java:68) ~[greenmail-1.5.13.jar:?]
	at com.icegreen.greenmail.imap.commands.SearchCommandParser.searchTerm(SearchCommandParser.java:100) [greenmail-1.5.13.jar:?]
	at com.icegreen.greenmail.imap.commands.SearchCommand.doProcess(SearchCommand.java:51) [greenmail-1.5.13.jar:?]

...


2020-07-02 19:26:54,182 WARN  [imap:127.0.0.1:1102<-/127.0.0.1:49855] commands.SearchCommandParser (SearchCommandParser.java:118) - Ignoring not yet implemented search command 'Message-ID'
java.lang.IllegalArgumentException: No enum constant com.icegreen.greenmail.imap.commands.SearchKey.Message-ID
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_242]
	at com.icegreen.greenmail.imap.commands.SearchKey.valueOf(SearchKey.java:68) ~[greenmail-1.5.13.jar:?]
	at com.icegreen.greenmail.imap.commands.SearchCommandParser.searchTerm(SearchCommandParser.java:100) [greenmail-1.5.13.jar:?]

...

2020-07-02 19:26:54,183 WARN  [imap:127.0.0.1:1102<-/127.0.0.1:49855] commands.SearchCommandParser (SearchCommandParser.java:118) - Ignoring not yet implemented search command '<4073506.0.1593682013956@[192.168.242.10]>'
java.lang.IllegalArgumentException: No enum constant com.icegreen.greenmail.imap.commands.SearchKey.<4073506.0.1593682013956@[192.168.242.10]>
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_242]
	at com.icegreen.greenmail.imap.commands.SearchKey.valueOf(SearchKey.java:68) ~[greenmail-1.5.13.jar:?]
	at com.icegreen.greenmail.imap.commands.SearchCommandParser.searchTerm(SearchCommandParser.java:100) [greenmail-1.5.13.jar:?]

...

2020-07-02 19:26:54,184 WARN  [imap:127.0.0.1:1102<-/127.0.0.1:49855] commands.SearchCommandParser (SearchCommandParser.java:118) - Ignoring not yet implemented search command 'SEEN)'
java.lang.IllegalArgumentException: No enum constant com.icegreen.greenmail.imap.commands.SearchKey.SEEN)
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_242]
	at com.icegreen.greenmail.imap.commands.SearchKey.valueOf(Sear
```

**Comment by marcelmay** [comment]
Thx alot, @Impakt !

**Comment by marcelmay** [comment]
Plan to roll the release 1.5 14 this weekend.

**Comment by Impakt** [comment]
sensational! I have subscribed to the releases rss feed and will update my project once it's out!
