### ISSUE TITLE
"java.lang.IllegalStateException: Can not read line, read 0 bytes" when trying to send SMTP mail since v1.6.3

### ISSUE THREAD

**Issue by ceisele-r** [greenmail-mail-test/greenmail#380]
We've been using greenmail before in version 1.6.0 until now.
After updating to v1.6.3, one of our tests fails as sending mails via smtp seems to have an issue there.

It does not seem to be a general issue with all sent mails as sending some mails still works, but the following exception is logged with verbose logging on using greenmail 1.6.3:
```
java.lang.IllegalStateException: Can not read line, read 0 bytes:
        at com.icegreen.greenmail.smtp.SmtpConnection.readLine(SmtpConnection.java:78)
        at com.icegreen.greenmail.smtp.SmtpHandler.handleCommand(SmtpHandler.java:77)
        at com.icegreen.greenmail.smtp.SmtpHandler.run(SmtpHandler.java:53)
        at com.icegreen.greenmail.server.AbstractServer.lambda$handleClientSocket$0(AbstractServer.java:160)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
        at com.icegreen.greenmail.smtp.SmtpConnection.readLine(SmtpConnection.java:53)
        ... 4 more
Exception in thread "smtp:example.com:3025<-/127.0.0.1:64108" java.lang.IllegalStateException: java.lang.IllegalStateException: Can not read line, read 0 bytes:
        at com.icegreen.greenmail.smtp.SmtpHandler.run(SmtpHandler.java:61)
        at com.icegreen.greenmail.server.AbstractServer.lambda$handleClientSocket$0(AbstractServer.java:160)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Can not read line, read 0 bytes:
        at com.icegreen.greenmail.smtp.SmtpConnection.readLine(SmtpConnection.java:78)
        at com.icegreen.greenmail.smtp.SmtpHandler.handleCommand(SmtpHandler.java:77)
        at com.icegreen.greenmail.smtp.SmtpHandler.run(SmtpHandler.java:53)
        ... 2 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
        at com.icegreen.greenmail.smtp.SmtpConnection.readLine(SmtpConnection.java:53)
        ... 4 more
```

I can't really trace it down what exactly causes this in greenmail. The mail is being sent using nodemailer, basically using such code (in node):
```
nodemailer.sendMail(options);
```

I traced it down and v1.6.2 it still works as before.
So it seems this error was introduced in the recently released v1.6.3.

Does this seem to be a greenmail internal issue?

**Comment by marcelmay** [comment]
@ceisele-r, can you provide the GreenMail verbose output (`-Dgreenmail.verbose`) or help me reproduce the issue with the simple [docker-compose setup](/greenmail-mail-test/greenmail/tree/master/greenmail-docker/clients/nodemailer)  ?

GreenMail 1.6.3 #371 might have introduced this.

**Comment by ceisele-r** [comment]
@marcelmay here's the verbose output:
```
0       INFO  GreenMailStandaloneRunner| Starting GreenMail standalone v1.6.3 using [ServerSetup{port=3025, bindAddress='ourdomain.com', protocol='smtp', readTimeout=-1, connectionTimeout=-1, writeTimeout=-1, serverStartupTimeout=2000, verbose=true}, ServerSetup{port=3143, bindAddress='ourdomain.com', protocol='imap', readTimeout=-1, connectionTimeout=-1, writeTimeout=-1, serverStartupTimeout=2000, verbose=true}]
10      DEBUG            util.GreenMail| Started services, performing check if all up
10      DEBUG           imap.ImapServer| Started imap:ourdomain.com:3143
10      DEBUG           smtp.SmtpServer| Started smtp:ourdomain.com:3025
130     INFO  GreenMailStandaloneRunner| Starting GreenMail API server at http://ourdomain.com:11111/
671066  DEBUG           imap.ImapServer| Handling new client connection imap:ourdomain.com:3143<-/127.0.0.1:62143
671071  DEBUG  util.LoggingOutputStream| S: * OK IMAP4rev1 Server GreenMail v1.6.3 ready\r\n
671073  DEBUG   imap.ImapRequestHandler| C: tag=A0, command=CAPABILITY
671074  DEBUG map.ImapRequestLineReader| IMAP Line received : <A0 CAPABILITY\r\n>
671074  DEBUG  util.LoggingOutputStream| S: * CAPABILITY IMAP4rev1 LITERAL+ SORT UIDPLUS QUOTA\r\n
671074  DEBUG  util.LoggingOutputStream| S: A0 OK CAPABILITY completed.\r\n
671075  DEBUG   imap.ImapRequestHandler| C: tag=A1, command=LOGIN
671075  DEBUG map.ImapRequestLineReader| IMAP Line received : <A1 LOGIN "mailbox@localhost.local" "mailbox"\r\n>
671075  DEBUG          user.UserManager| Authenticating user mailbox@localhost.local
671076  DEBUG  util.LoggingOutputStream| S: A1 OK LOGIN completed.\r\n
671076  DEBUG   imap.ImapRequestHandler| C: tag=A2, command=CAPABILITY
671076  DEBUG map.ImapRequestLineReader| IMAP Line received : <A2 CAPABILITY\r\n>
671076  DEBUG  util.LoggingOutputStream| S: * CAPABILITY IMAP4rev1 LITERAL+ SORT UIDPLUS QUOTA\r\n
671076  DEBUG  util.LoggingOutputStream| S: A2 OK CAPABILITY completed.\r\n
671077  DEBUG   imap.ImapRequestHandler| C: tag=A3, command=LIST
671078  DEBUG map.ImapRequestLineReader| IMAP Line received : <A3 LIST "" ""\r\n>
671078  DEBUG  util.LoggingOutputStream| S: * LIST (\Noselect) "." ""\r\n
671078  DEBUG  util.LoggingOutputStream| S: A3 OK LIST completed.\r\n
671080  DEBUG   imap.ImapRequestHandler| C: tag=A4, command=LIST
671081  DEBUG map.ImapRequestLineReader| IMAP Line received : <A4 LIST "" "*"\r\n>
671082  DEBUG  util.LoggingOutputStream| S: * LIST () "." "INBOX"\r\n
671083  DEBUG  util.LoggingOutputStream| S: A4 OK LIST completed.\r\n
671083  DEBUG   imap.ImapRequestHandler| C: tag=A5, command=SELECT
671083  DEBUG map.ImapRequestLineReader| IMAP Line received : <A5 SELECT "INBOX"\r\n>
671084  DEBUG  util.LoggingOutputStream| S: * FLAGS (\Answered \Deleted \Draft \Flagged \Seen)\r\n
671085  DEBUG  util.LoggingOutputStream| S: * 0 EXISTS\r\n
671085  DEBUG  util.LoggingOutputStream| S: * 0 RECENT\r\n
671085  DEBUG  util.LoggingOutputStream| S: * OK [UIDVALIDITY 1617688852]\r\n
671085  DEBUG  util.LoggingOutputStream| S: * OK [UIDNEXT 1]\r\n
671085  DEBUG  util.LoggingOutputStream| S: * OK No messages unseen\r\n
671085  DEBUG  util.LoggingOutputStream| S: * OK [PERMANENTFLAGS (\Answered \Deleted \Draft \Flagged \Seen)]\r\n
671085  DEBUG  util.LoggingOutputStream| S: A5 OK [READ-WRITE] SELECT completed.\r\n
671086  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
671086  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
671086  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
681088  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
681088  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
681088  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
681308  DEBUG           smtp.SmtpServer| Handling new client connection smtp:ourdomain.com:3025<-/127.0.0.1:62144
681315  DEBUG          user.UserManager| Authenticating user send@localhost.local
691100  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
691100  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
691100  DEBUG  util.LoggingOutputStream| S: * 1 EXISTS\r\n
691100  DEBUG  util.LoggingOutputStream| S: * 1 RECENT\r\n
691101  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
691102  DEBUG   imap.ImapRequestHandler| C: tag=A6, command=UID
691108  DEBUG ommands.SearchTermBuilder| Creating search term for 'UNSEEN'
691108  DEBUG map.ImapRequestLineReader| IMAP Line received : <A6 UID SEARCH UNSEEN\r\n>
691109  DEBUG  util.LoggingOutputStream| S: * SEARCH 1\r\n
691109  DEBUG  util.LoggingOutputStream| S: A6 OK SEARCH completed.\r\n
691110  DEBUG   imap.ImapRequestHandler| C: tag=A7, command=UID
691111  DEBUG map.ImapRequestLineReader| IMAP Line received : <A7 UID FETCH 1 (UID FLAGS INTERNALDATE BODYSTRUCTURE BODY[])\r\n>
691112  DEBUG     commands.FetchCommand| Fetching body part for section specifier  and mime message (contentType=text/html; charset=utf-8
691112  DEBUG  util.LoggingOutputStream| S: * 1 FETCH (FLAGS (\Seen) INTERNALDATE "06-Apr-2021 08:01:02 +0200" BODYSTRUCTURE ("TEXT" "HTML" ("charset" "utf-8") NIL NIL "quot[WRAP]
691112  DEBUG  util.LoggingOutputStream| S: ed-printable" 8524 328 NIL NIL NIL) UID 1 BODY[] {9020}\r\n
691112  DEBUG  util.LoggingOutputStream| S: Return-Path: <no-reply@ourdomain.com>\r\n
691112  DEBUG  util.LoggingOutputStream| S: Received: from 127.0.0.1 (HELO [127.0.0.1]); Tue Apr 06 08:01:02 CEST 2021\r\n
691112  DEBUG  util.LoggingOutputStream| S: Content-Type: text/html; charset=utf-8\r\n
691112  DEBUG  util.LoggingOutputStream| S: From: Testuser_B6C1FD8D640AFE7B <no-reply@ourdomain.com>\r\n
691113  DEBUG  util.LoggingOutputStream| S: To: mailbox@localhost.local\r\n
691113  DEBUG  util.LoggingOutputStream| S: Reply-To: mailbox@localhost.local\r\n
691113  DEBUG  util.LoggingOutputStream| S: Subject: [i-3A043FE99497CFB7]\r\n
691113  DEBUG  util.LoggingOutputStream| S: Message-ID: <15a5d8c0-1a3f-82dd-28d6-7745c27d1e47@ourdomain.com>\r\n
691113  DEBUG  util.LoggingOutputStream| S: Content-Transfer-Encoding: quoted-printable\r\n
691113  DEBUG  util.LoggingOutputStream| S: Date: Tue, 06 Apr 2021 06:01:02 +0000\r\n
691113  DEBUG  util.LoggingOutputStream| S: MIME-Version: 1.0\r\n
691113  DEBUG  util.LoggingOutputStream| S: \r\n
691113  DEBUG  util.LoggingOutputStream| S: ----------PLACEHOLDER------REMOVED------------HTML_MAILCONTENTS
691124  DEBUG  util.LoggingOutputStream| S: )\r\n
691124  DEBUG  util.LoggingOutputStream| S: A7 OK FETCH completed.\r\n
691139  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
691139  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
691139  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
691331  INFO           smtp.SmtpManager| Created user login test@ourdomain.com for address test@ourdomain.com with password test@ourdomain.com because it didn't exist before.
691510  DEBUG   imap.ImapRequestHandler| C: tag=A8, command=STORE
691511  DEBUG map.ImapRequestLineReader| IMAP Line received : <A8 STORE 1 FLAGS.SILENT (\DELETED)\r\n>
691512  DEBUG  util.LoggingOutputStream| S: A8 OK STORE completed.\r\n
691512  DEBUG   imap.ImapRequestHandler| C: tag=A9, command=EXPUNGE
691512  DEBUG map.ImapRequestLineReader| IMAP Line received : <A9 EXPUNGE\r\n>
691512  DEBUG  util.LoggingOutputStream| S: * 1 EXPUNGE\r\n
691512  DEBUG  util.LoggingOutputStream| S: A9 OK EXPUNGE completed.\r\n
701142  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
701142  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
701142  DEBUG  util.LoggingOutputStream| S: * 1 EXISTS\r\n
701143  DEBUG  util.LoggingOutputStream| S: * 1 RECENT\r\n
701143  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
701144  DEBUG   imap.ImapRequestHandler| C: tag=A10, command=UID
701144  DEBUG ommands.SearchTermBuilder| Creating search term for 'UNSEEN'
701144  DEBUG map.ImapRequestLineReader| IMAP Line received : <A10 UID SEARCH UNSEEN\r\n>
701144  DEBUG  util.LoggingOutputStream| S: * SEARCH 2\r\n
701144  DEBUG  util.LoggingOutputStream| S: A10 OK SEARCH completed.\r\n
701145  DEBUG   imap.ImapRequestHandler| C: tag=A11, command=UID
701145  DEBUG map.ImapRequestLineReader| IMAP Line received : <A11 UID FETCH 2 (UID FLAGS INTERNALDATE BODYSTRUCTURE BODY[])\r\n>
701145  DEBUG     commands.FetchCommand| Fetching body part for section specifier  and mime message (contentType=text/html; charset=utf-8
701145  DEBUG  util.LoggingOutputStream| S: * 1 FETCH (FLAGS (\Seen) INTERNALDATE "06-Apr-2021 08:01:18 +0200" BODYSTRUCTURE ("TEXT" "HTML" ("charset" "utf-8") NIL NIL "quot[WRAP]
701145  DEBUG  util.LoggingOutputStream| S: ed-printable" 8524 328 NIL NIL NIL) UID 2 BODY[] {9020}\r\n
701145  DEBUG  util.LoggingOutputStream| S: Return-Path: <no-reply@ourdomain.com>\r\n
701145  DEBUG  util.LoggingOutputStream| S: Received: from 127.0.0.1 (HELO [127.0.0.1]); Tue Apr 06 08:01:18 CEST 2021\r\n
701145  DEBUG  util.LoggingOutputStream| S: Content-Type: text/html; charset=utf-8\r\n
701145  DEBUG  util.LoggingOutputStream| S: From: Testuser_B6C1FD8D640AFE7B <no-reply@ourdomain.com>\r\n
701146  DEBUG  util.LoggingOutputStream| S: To: mailbox@localhost.local\r\n
701146  DEBUG  util.LoggingOutputStream| S: Reply-To: mailbox@localhost.local\r\n
701146  DEBUG  util.LoggingOutputStream| S: Subject: [i-6B409D13A244A46B]\r\n
701146  DEBUG  util.LoggingOutputStream| S: Message-ID: <89c02b31-f6bd-4241-e3ba-86703f1b0503@ourdomain.com>\r\n
701146  DEBUG  util.LoggingOutputStream| S: Content-Transfer-Encoding: quoted-printable\r\n
701146  DEBUG  util.LoggingOutputStream| S: Date: Tue, 06 Apr 2021 06:01:18 +0000\r\n
701146  DEBUG  util.LoggingOutputStream| S: MIME-Version: 1.0\r\n
701146  DEBUG  util.LoggingOutputStream| S: \r\n
701146  DEBUG  util.LoggingOutputStream| S: ----------PLACEHOLDER------REMOVED------------HTML_MAILCONTENTS
701152  DEBUG  util.LoggingOutputStream| S: )\r\n
701152  DEBUG  util.LoggingOutputStream| S: A11 OK FETCH completed.\r\n
701162  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
701162  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
701162  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
701437  DEBUG   imap.ImapRequestHandler| C: tag=A12, command=STORE
701437  DEBUG map.ImapRequestLineReader| IMAP Line received : <A12 STORE 1 FLAGS.SILENT (\DELETED)\r\n>
701437  DEBUG  util.LoggingOutputStream| S: A12 OK STORE completed.\r\n
701437  DEBUG   imap.ImapRequestHandler| C: tag=A13, command=EXPUNGE
701437  DEBUG map.ImapRequestLineReader| IMAP Line received : <A13 EXPUNGE\r\n>
701437  DEBUG  util.LoggingOutputStream| S: * 1 EXPUNGE\r\n
701437  DEBUG  util.LoggingOutputStream| S: A13 OK EXPUNGE completed.\r\n
711183  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
711183  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
711183  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
721190  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
721190  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
721190  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
731209  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
731209  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
731209  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
731276  ERROR          smtp.SmtpHandler| Unexpected error handling connection, quitting=
java.lang.IllegalStateException: Can not read line, read 0 bytes: 
	at com.icegreen.greenmail.smtp.SmtpConnection.readLine(SmtpConnection.java:78)
	at com.icegreen.greenmail.smtp.SmtpHandler.handleCommand(SmtpHandler.java:77)
	at com.icegreen.greenmail.smtp.SmtpHandler.run(SmtpHandler.java:53)
	at com.icegreen.greenmail.server.AbstractServer.lambda$handleClientSocket$0(AbstractServer.java:160)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
	at com.icegreen.greenmail.smtp.SmtpConnection.readLine(SmtpConnection.java:53)
	... 4 more
741209  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
741209  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
741209  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
751211  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
751211  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
751211  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
761212  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
761212  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
761212  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
771218  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
771218  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
771218  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
781220  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
781220  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
781220  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
791231  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
791231  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
791231  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
801243  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
801243  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
801243  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
811280  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
811280  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
811280  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
821319  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
821319  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
821319  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
831336  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
831336  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
831336  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
841344  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
841344  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
841344  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
851359  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
851359  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
851359  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
861368  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
861368  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
861368  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
871382  DEBUG   imap.ImapRequestHandler| C: tag=NOOP, command=NOOP
871382  DEBUG map.ImapRequestLineReader| IMAP Line received : <NOOP NOOP\r\n>
871382  DEBUG  util.LoggingOutputStream| S: NOOP OK NOOP completed.\r\n
876921  DEBUG map.ImapRequestLineReader| IMAP Line received : <￿>
```

Please note that I removed the html mail contents to shorten the log.
If you need anything there, please let me know.

I can unfortunately not help with a simle reproduction using the docker-compose-setup as I am not really sure what exactly causes the issue and the application under test (=the application sending the mails) requires a rather complex setup.

Let me know if you need anything else.

**Comment by apinske** [comment]
The problem stems from keeping the SMTP connection open for a longer than 30 seconds (`AbstractServer.CLIENT_SOCKET_SO_TIMEOUT`) without issuing any command. The RFC recommends at least 5 minutes (https://datatracker.ietf.org/doc/html/rfc5321#section-4.5.3.2.7).

The problem was indeed introduced in 1638d532906b8a93eff79a4f78d507c28d9a901b. In `SmtpConnection#readLine` a potential `SocketTimeoutException` is now converted into an `IllegalStateException` preventing `SmtpHandler#run` from handling it (by terminating the connection).
Possible workaround is to close the connections earlier (or not reuse at all).

I will attempt a fix.

**Comment by marcelmay** [comment]
Thx alot, @apinske !
