### ISSUE TITLE
SMTPS failure on JVM 11.0.11

### ISSUE THREAD

**Issue by james-mullen-itv** [greenmail-mail-test/greenmail#388]
We have updated our JVM version to 11.0.11 - in this release support for TLS 1.0 and 1.1 was removed.

We have a unit test using greenmail which attempts to perform an SMTPS email send via Javamail to Greenmail.

This now fails with this exception : 

```
10:20:52.500 [Test worker] ERROR XXX.JavaMailSender - Failed to create and send mail message for to@localhost.com, subject subject.
    javax.mail.MessagingException: Could not connect to SMTP host: 127.0.0.1, port: 3465
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1961)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:654)
        at javax.mail.Service.connect(Service.java:295)
        at javax.mail.Service.connect(Service.java:176)
        at javax.mail.Service.connect(Service.java:196)
        at XXX.JavaMailSender.connectTransport(JavaMailSender.java:121)
        at XXX.JavaMailSender.sendMessage(JavaMailSender.java:109)
        at XXX.JavaMailSender.sendEmail(JavaMailSender.java:67)
        at XXX.JavaMailSenderAuthTest.shouldSendSmtpWithAuth(JavaMailSenderAuthTest.java:67)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
        at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy5.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:829)
    Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
        at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:170)
        at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:98)
        at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:221)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:433)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:527)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:332)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:234)
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1927)
        ... 96 common frames omitted
```

I assume there are now no compatible ciphers between the ones greenmail is configuring and that come with 11.0.11.

**Comment by marcelmay** [comment]
Thanks for the feedback.

Running with eg 'OpenJDK 64-Bit Server VM Corretto-11.0.11.9.1' works, so I need further details.

- Could you run GreenMail using ```-Djavax.net.debug=all``` output when starting GreenMail?
   For example you could run
   ```java -Djavax.net.debug=all -Dgreenmail.setup.test.all -Dgreenmail.verbose  -Dgreenmail.users=foo:pwd@bar.com -jar greenmail-standalone-YOUR-VERSION.jar```
- And provide the output of eg ```openssl s_client -connect localhost:3465``` (whichever GreenMail port runs secure)?
- Has your JVM specifically disabled TLS <= 1.2 ?

**Comment by marcelmay** [comment]
.... and provide output of `java -version`

**Comment by james-mullen-itv** [comment]
For your test above you used Corretto which for now isn't disabling TLS 1.0/1.1 see here : https://aws.amazon.com/blogs/opensource/tls-1-0-1-1-changes-in-openjdk-and-amazon-corretto/.

I was using OpenJDK 11.0.11 which has disabled 1.0/1.1.


```
openssl s_client -connect localhost:3465
CONNECTED(00000005)
depth=0 C = US, O = Icegreen Technologies, OU = GreenMail, CN = GreenMail selfsigned Test Certificate
verify error:num=18:self signed certificate
verify return:1
depth=0 C = US, O = Icegreen Technologies, OU = GreenMail, CN = GreenMail selfsigned Test Certificate
verify return:1
---
Certificate chain
 0 s:/C=US/O=Icegreen Technologies/OU=GreenMail/CN=GreenMail selfsigned Test Certificate
   i:/C=US/O=Icegreen Technologies/OU=GreenMail/CN=GreenMail selfsigned Test Certificate
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDgTCCAmmgAwIBAgIEbTqUozANBgkqhkiG9w0BAQsFADBxMQswCQYDVQQGEwJV
UzEeMBwGA1UEChMVSWNlZ3JlZW4gVGVjaG5vbG9naWVzMRIwEAYDVQQLEwlHcmVl
bk1haWwxLjAsBgNVBAMTJUdyZWVuTWFpbCBzZWxmc2lnbmVkIFRlc3QgQ2VydGlm
aWNhdGUwHhcNMjEwNDI2MTA1ODMxWhcNMjMwNzMwMTA1ODMxWjBxMQswCQYDVQQG
EwJVUzEeMBwGA1UEChMVSWNlZ3JlZW4gVGVjaG5vbG9naWVzMRIwEAYDVQQLEwlH
cmVlbk1haWwxLjAsBgNVBAMTJUdyZWVuTWFpbCBzZWxmc2lnbmVkIFRlc3QgQ2Vy
dGlmaWNhdGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDRg938mVgT
2Fa13b5i4egnUKoDlQ1y7RK5ZyvxRimwsR0IDyAtidBahwPok6I2X5IMw25EuJy/
aYerzm+MqoEfDlkzPTliayBZ8CB0hsJQmsmw2b26LYVSlMdyw7iORyLXERbtQFOL
ZAcuhyOSoztPbnrP42yNdD/59UVXYlxSMQQVwQ6rWDrg6BjKXahX0ptJ9v7rWqTB
wn47RJUQ/IY6ZMuZP38iY9HZHVn3EdYoT38DvhMLyscOcpzPdBG1t1R3CBUUEL4R
ydnP42SDGHAfTdVxCqL+WAWwPTf9Z7BcPdoJsn5igRVynLvj7d2TQfXnCiAAy8T5
Fd/S2GNsOmMdAgMBAAGjITAfMB0GA1UdDgQWBBQQ6KrYgDvIvdDGkb6wwtFl03TZ
5DANBgkqhkiG9w0BAQsFAAOCAQEAWsO0i9e0zyRjZEOp2SkGXo77WzfPJiuDvvcG
ZOinBMxW1r+oY3JWkwAtKBAMxDZbCMC+jIDJ63NLZD07y9uUoTJxakMOXIcEHShE
4OLWOfbU2HBRDpBbouKx0olQ84+nAbC7w5X/dxU20M1IkXlu8IfoICqaTS2tDZoU
THkUz9wcAdVM1/DXSh4CGdEqK6rWH4VERjFrU1LA/maoLg5b2EDVjF4Ex5YX0U8w
p4mnV1oMkWkWW1BkqG3ovTDjYGVeQ94xpR6zk1EzchYj9pbKv3PEFANDaUAbGXEv
t7JaZs30BGdXjeKdDAvoE5T7Fj2kBWN2goPPv2Ep2AuCAR57HA==
-----END CERTIFICATE-----
subject=/C=US/O=Icegreen Technologies/OU=GreenMail/CN=GreenMail selfsigned Test Certificate
issuer=/C=US/O=Icegreen Technologies/OU=GreenMail/CN=GreenMail selfsigned Test Certificate
---
No client certificate CA names sent
Server Temp Key: ECDH, X25519, 253 bits
---
SSL handshake has read 1367 bytes and written 289 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 726B03FEC08FE08646471DD6F4D2D4E7AFFA05593C63C9074A475E2155615321
    Session-ID-ctx: 
    Master-Key: 662D5F262BC7F633528861B2D1FECBB552399E1B177213A215E7C1BF3A9883AC551E871E1A3D41E04ABCF712CEE13D5A
    Start Time: 1620132260
    Timeout   : 7200 (sec)
    Verify return code: 18 (self signed certificate)
---
220 /172.17.0.2 GreenMail SMTP Service v1.6.3 ready
```

The above was run against a docker build of greenmail using this base image : `FROM openjdk:11.0.11-jre-slim-buster`

**Comment by marcelmay** [comment]
In your example above using openssl client,
you successfully ran agains GreenMail in an openjdk container using SMTPS.

GreenMail replied on SMTP-over-TLS port 3465  with
```220 /172.17.0.2 GreenMail SMTP Service v1.6.3 ready``` 

You might also note that  here GreenMail uses TLSv1.2 - I believe only TLS 1.0 and TLS 1.1 got disabled in JDK 11 ?

I tried to reproduce this with adoptopenjdk 11 (11.0.11), GreenMail Standalone runner and using secure IMAP and SMTP, and can successfully connect using Thunderbird. Eg the GreenMail sources would also fail building with adoptopenjdk 11 (as there are tests using TLS).

**Comment by marcelmay** [comment]
FYI, I just also just updated  in 29bde8b91dd34b3611cf738c13844b45d5788843 the CirclleCI JDK 11 build to use openjdk:11.0.11-jdk-slim-buster :

https://app.circleci.com/pipelines/github/greenmail-mail-test/greenmail/143/workflows/361fcf73-f732-4745-8688-ddfc193ffe63/jobs/848

**Comment by james-mullen-itv** [comment]
Thanks for the comments just back around to looking at this. It turned out this was a Javamail issue upgrading to the latest version (1.6) resolved the issue were we seeing.
