### ISSUE TITLE
IMAP attachment empty

### ISSUE THREAD

**Issue by MrJavaNoHome** [greenmail-mail-test/greenmail#419]
Seems like greenmail bug. I've tried it with another local server and received attachment successfully. Any workaround?

Test: https://github.com/MrJavaNoHome/greenmail-imap-attachment/blob/master/src/test/java/io/github/mrjavanohome/ImapFetchTest.java

Greenmail version: 1.6.5
Java version: openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

Logs
```
DEBUG: Jakarta Mail version 1.6.7
DEBUG: successfully loaded resource: /META-INF/javamail.default.providers
DEBUG: Tables of loaded providers
DEBUG: Providers Listed By Class Name: {com.sun.mail.smtp.SMTPTransport=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], com.sun.mail.imap.IMAPSSLStore=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], com.sun.mail.pop3.POP3Store=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], com.sun.mail.smtp.SMTPSSLTransport=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], com.sun.mail.imap.IMAPStore=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], com.sun.mail.pop3.POP3SSLStore=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle]}
DEBUG: Providers Listed By Protocol: {imap=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], smtp=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], pop3=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], imaps=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], smtps=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], pop3s=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle]}
DEBUG: successfully loaded resource: /META-INF/javamail.default.address.map
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "127.0.0.1", port 3025, isSSL false
220 /127.0.0.1 GreenMail SMTP Service v1.6.5 ready
DEBUG SMTP: connected to host "127.0.0.1", port: 3025
EHLO 127.0.0.1
250-/127.0.0.1
250 AUTH PLAIN LOGIN
DEBUG SMTP: Found extension "AUTH", arg "PLAIN LOGIN"
DEBUG SMTP: use8bit false
MAIL FROM:<foo@example.com>
250 OK
RCPT TO:<bar@example.com>
250 OK
DEBUG SMTP: Verified Addresses
DEBUG SMTP:   bar@example.com
DATA
354 Start mail input; end with <CRLF>.<CRLF>
Date: Fri, 24 Dec 2021 12:25:59 +0100 (CET)
From: foo@example.com
To: bar@example.com
Message-ID: <690052870.1.1640345159199@127.0.0.1>
Subject: Email to local mail server
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_0_710190911.1640345159160"

------=_Part_0_710190911.1640345159160
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

Fetch me via IMAP
------=_Part_0_710190911.1640345159160
Content-Type: application/octet-stream; 
	name=test-attachment6687297221761434067txt
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; 
	filename=test-attachment6687297221761434067txt

Hello Github
------=_Part_0_710190911.1640345159160--
.
250 OK
DEBUG SMTP: message successfully delivered to mail server
QUIT
221 /127.0.0.1 Service closing transmission channel
DEBUG: Jakarta Mail version 1.6.7
DEBUG: successfully loaded resource: /META-INF/javamail.default.providers
DEBUG: Tables of loaded providers
DEBUG: Providers Listed By Class Name: {com.sun.mail.smtp.SMTPTransport=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], com.sun.mail.imap.IMAPSSLStore=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], com.sun.mail.pop3.POP3Store=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], com.sun.mail.smtp.SMTPSSLTransport=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], com.sun.mail.imap.IMAPStore=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], com.sun.mail.pop3.POP3SSLStore=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle]}
DEBUG: Providers Listed By Protocol: {imap=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], smtp=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], pop3=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], imaps=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], smtps=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], pop3s=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle]}
DEBUG: successfully loaded resource: /META-INF/javamail.default.address.map
DEBUG: setDebug: Jakarta Mail version 1.6.7
DEBUG: getProvider() returning javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle]
DEBUG IMAP: mail.imap.partialfetch: false
DEBUG IMAP: mail.imap.ignorebodystructuresize: false
DEBUG IMAP: mail.imap.statuscachetimeout: 1000
DEBUG IMAP: mail.imap.appendbuffersize: -1
DEBUG IMAP: mail.imap.minidletime: 10
DEBUG IMAP: closeFoldersOnStoreFailure
DEBUG IMAP: trying to connect to host "127.0.0.1", port 3143, isSSL false
* OK IMAP4rev1 Server GreenMail v1.6.5 ready
A0 CAPABILITY
* CAPABILITY IMAP4rev1 LITERAL+ SORT UIDPLUS IDLE QUOTA
A0 OK CAPABILITY completed.
DEBUG IMAP: protocolConnect login, host=127.0.0.1, user=bar@example.com, password=<non-null>
DEBUG IMAP: mechanism PLAIN not supported by server
DEBUG IMAP: mechanism LOGIN not supported by server
DEBUG IMAP: mechanism NTLM not supported by server
DEBUG IMAP: mechanism XOAUTH2 disabled by property: mail.imap.auth.xoauth2.disable
DEBUG IMAP: LOGIN command trace suppressed
DEBUG IMAP: LOGIN command result: A1 OK LOGIN completed.
A2 CAPABILITY
* CAPABILITY IMAP4rev1 LITERAL+ SORT UIDPLUS IDLE QUOTA
A2 OK CAPABILITY completed.
DEBUG IMAP: connection available -- size: 1
A3 EXAMINE INBOX
* FLAGS (\Answered \Deleted \Draft \Flagged \Seen \*)
* 1 EXISTS
* 1 RECENT
* OK [UIDVALIDITY 1640345159]
* OK [UIDNEXT 2]
* OK [UNSEEN 1] Message 1 is the first unseen
* OK [PERMANENTFLAGS (\Answered \Deleted \Draft \Flagged \Seen \*)]
A3 OK [READ-ONLY] EXAMINE completed.
1
A4 SEARCH DELETED ALL
* SEARCH
A4 OK SEARCH completed.
0
A5 SEARCH UNSEEN ALL
* SEARCH 1
A5 OK SEARCH completed.
1
A6 FETCH 1 (BODYSTRUCTURE)
* 1 FETCH (BODYSTRUCTURE (("TEXT" "PLAIN" ("charset" "us-ascii") NIL NIL "7bit" 17 1 NIL NIL NIL)("APPLICATION" "OCTET-STREAM" ("name" "test-attachment6687297221761434067txt") NIL NIL "7bit" 12 NIL ("attachment" ("filename" "test-attachment6687297221761434067txt")) NIL) "mixed" ("boundary" "----=_Part_0_710190911.1640345159160") NIL NIL) UID 1)
A6 OK FETCH completed.
A7 FETCH 1 (BODY[2])
* 1 FETCH (UID 1 BODY[2] {0}
)
A7 OK FETCH completed.
A8 FETCH 1 (ENVELOPE INTERNALDATE RFC822.SIZE)
* 1 FETCH (INTERNALDATE "24-Dec-2021 12:25:59 +0100" RFC822.SIZE 438 ENVELOPE ("Fri, 24 Dec 2021 12:25:59 +0100 (CET)" "Email to local mail server" ((NIL NIL "foo" "example.com")) ((NIL NIL "foo" "example.com")) ((NIL NIL "foo" "example.com")) ((NIL NIL "bar" "example.com")) NIL NIL NIL "<690052870.1.1640345159199@127.0.0.1>") UID 1)
A8 OK FETCH completed.
```

	org.opentest4j.AssertionFailedError: 
	Expected :Hello Github
	Actual   :
	
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
	at io.github.mrjavanohome.ImapFetchTest.sendAndReceiveUsingGreenMail(ImapFetchTest.java:59)

**Comment by marcelmay** [comment]
Thanks for the report and example.

When I run it, it seems to work as expected (no test failure):

```
$ mvn test      
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------< io.github.mrjavanohome:greenmail-imap-attachment >----------
[INFO] Building greenmail-imap-attachment 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
... 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ greenmail-imap-attachment ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.github.mrjavanohome.ImapFetchTest
...
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.196 s - in io.github.mrjavanohome.ImapFetchTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
...

$ mvn -v  
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
...
Java version: 11.0.13, vendor: Amazon.com Inc., runtime: /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
...
```
Only change was adding surefire to the POM for running the test:
```
$ git diff
diff --git a/pom.xml b/pom.xml
index 1ee6186..9a3641a 100644
--- a/pom.xml
+++ b/pom.xml
@@ -29,4 +29,13 @@
         </dependency>
     </dependencies>
 
-</project>
\ No newline at end of file
+    <build>
+        <plugins>
+            <plugin>
+                <artifactId>maven-surefire-plugin</artifactId>
+                <version>3.0.0-M5</version>
+            </plugin>
+        </plugins>
+    </build>
+
+</project>
```

**Comment by marcelmay** [comment]
What is your default locale?  E.g. what does Maven spit out?
```
$ mvn -v|grep locale
Default locale: en_DE, platform encoding: UTF-8
```

**Comment by MrJavaNoHome** [comment]
It says. Could it be encoding problem?
`Default locale: en_US, platform encoding: Cp1250`

**Comment by marcelmay** [comment]
Yes, it seems so.

You could try running with system property  for UTF-8 encoding:
```-Dfile.encoding=UTF-8```

**Comment by MrJavaNoHome** [comment]
Changed it for whole project but no luck. Test still fails.
