### ISSUE TITLE
Check/improve compatibility with mail clients

### ISSUE THREAD

**Issue by camann9** [greenmail-mail-test/greenmail#44]
Greenmail was written with JavaMail as the primary client. Nonetheless it would be nice if users would be able to connect to Greenmail using a mail client of their choice. We should check/improve support for major mail clients:
- Thunderbird
- Outlook
- Apple mail

**Comment by buildscientist** [comment]
Apple Mail v7.3 on OS X 10.9.5 connecting to IMAP on 3143 (non SSL) using greenmail-standalone v1.5.0 causes the following exception/warning to be logged: 

```
159694  WARN      commands.FetchCommand| Error processing command: Unexpected end of line. Command should be '<tag> FETCH <message-set> <fetch-profile>'
com.icegreen.greenmail.imap.ProtocolException: Unexpected end of line.
	at com.icegreen.greenmail.imap.commands.FetchCommand$FetchCommandParser.nextCharInLine(FetchCommand.java:451)
	at com.icegreen.greenmail.imap.commands.FetchCommand$FetchCommandParser.addNextElement(FetchCommand.java:363)
	at com.icegreen.greenmail.imap.commands.FetchCommand$FetchCommandParser.fetchRequest(FetchCommand.java:350)
	at com.icegreen.greenmail.imap.commands.FetchCommand.doProcess(FetchCommand.java:58)
	at com.icegreen.greenmail.imap.commands.FetchCommand.doProcess(FetchCommand.java:48)
	at com.icegreen.greenmail.imap.commands.CommandTemplate.process(CommandTemplate.java:57)
	at com.icegreen.greenmail.imap.ImapRequestHandler.doProcessRequest(ImapRequestHandler.java:98)
	at com.icegreen.greenmail.imap.ImapRequestHandler.handleRequest(ImapRequestHandler.java:51)
	at com.icegreen.greenmail.imap.ImapHandler.run(ImapHandler.java:69)
	at com.icegreen.greenmail.server.AbstractServer$1.run(AbstractServer.java:158)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by marcelmay** [comment]
Opened issue #126 for this.
