### ISSUE TITLE
JBoss sar does not work on 7.1.3

### ISSUE THREAD

**Issue by sellersj** [greenmail-mail-test/greenmail#63]
Looks like the sar is the wrong format for jboss 7. In the documentation it should list which versions of jboss it supports.

It looks like the old XMBeans support was dropped.

I get the following error
```
10:08:34,896 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-4) MSC00001: Failed to start service jboss.deployment.unit."greenmail-jboss-service-1.4.0.sar".PARSE: org.jboss.msc.service.StartException in service jboss.deployment.unit."greenmail-jboss-service-1.4.0.sar".PARSE: JBAS018733: Failed to process phase PARSE of deployment "greenmail-jboss-service-1.4.0.sar"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:123) [jboss-as-server-7.1.3.Final.jar:7.1.3.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_76]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_76]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_76]
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: JBAS017224: Failed to parse service xml ["/C:/devtools/jboss/jboss-as-7.1.3.Final/bin/content/greenmail-jboss-service-1.4.0.sar/META-INF/jboss-service.xml"]
	at org.jboss.as.service.ServiceDeploymentParsingProcessor.deploy(ServiceDeploymentParsingProcessor.java:102)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:116) [jboss-as-server-7.1.3.Final.jar:7.1.3.Final]
	... 5 more
Caused by: com.ctc.wstx.exc.WstxParsingException: Received event DTD, instead of START_ELEMENT or END_ELEMENT.
 at [row,col {unknown-source}]: [3,16]
	at com.ctc.wstx.sr.StreamScanner.constructWfcException(StreamScanner.java:606)
	at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:479)
	at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:464)
	at com.ctc.wstx.sr.BasicStreamReader.nextTag(BasicStreamReader.java:1143)
	at org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:67)
	at org.jboss.as.service.ServiceDeploymentParsingProcessor.deploy(ServiceDeploymentParsingProcessor.java:95)
	... 6 more
```

**Comment by marcelmay** [comment]
Thanks for spotting this!

I'll update the documentation that the SAR only works up to JBoss AS 6.
As a solution it looks like GreenMail will have to provide an additional SAR for JBoss AS 7.x .

**Comment by marcelmay** [comment]
I managed to get an adapted GreenMail SAR running on JBoss AS 7.1.1 . I'll commit/publish a SNAPSHOT over the weekend.

**Comment by marcelmay** [comment]
This issue covers only documentation.

For JBoss 7 support, a new issue should be created as we need a new JBoss 7 artifact. I'm not sure yet if it is necessary, as the main benefit of the (old) SAR was a nice integration into the JBoss Web Console which does not exist anymore for JBoss 7+.  An alternative is the GreenMail WAR deployment.
