### ISSUE TITLE
Using `GreenMailExtension` in a Spring Boot Test, in Kotlin

### ISSUE THREAD

**Issue by smcvb** [greenmail-mail-test/greenmail#690]
First and foremost, thanks for taking the time to look at this.
Secondly, it wasn't entirely clear to me whether it's okay to use this issue tracker for what I assume to be usage issues.
If this was incorrect feel free to redirect me to another source.

Now, concerning my scenario.

I am using the `JavaMailSender` in a scheduled job (through [JobRunr](https://www.jobrunr.io/en/)) inside a Kotlin-based (version 1.9.22) Spring Boot (version 3.2.2) application.

The predicament I am running against is writing an Integration Test that (1) actually sends an email and (2) allows me to validate what's been sent.
I have been playing around with roughly two routes, as described [here](https://rieckpil.de/use-greenmail-for-spring-mail-javamailsender-junit-5-integration-tests/), thus being:

1. By registering the `GreenMailExtension` with the recommended default Spring Boot properties.
2. By constructing a Test Container and setting up a `Session` next to this to retrieve the email.

I am aiming towards the extension approach though, as that seems a little cleaner to me than setting up the `Session` to retrieve the dispatched email (although getting the greenmail container to run is straightforward).

Thus focusing on option 1, I currently have the following in my test case for registering the extension:

```kotlin
@JvmField
@RegisterExtension
protected final val greenMail: GreenMailExtension = GreenMailExtension(ServerSetupTest.SMTP)
        .withConfiguration(GreenMailConfiguration().withUser("user", "admin"))
        .withPerMethodLifecycle(false)
```

Which is combined with the following `application.properties`:

```properties
spring.mail.host=127.0.0.1
spring.mail.port=3025
spring.mail.username=user
spring.mail.password=admin
spring.mail.protocol=smtp
spring.mail.test-connection=false
```

Lastly, I am only pulling in the `greenmail-junit5` (version 2.0.1), as that seemed sufficient to me.

Doing the above and running my test, the production code prompts me with the following exception:

```txt
org.springframework.mail.MailSendException: Mail server connection failed. Failed messages: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: 127.0.0.1, 3025; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection refused; message exception details (1) are:
Failed message 1:
com.sun.mail.util.MailConnectException: Couldn't connect to host, port: 127.0.0.1, 3025; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection refused
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2210)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722)
	at jakarta.mail.Service.connect(Service.java:345)
	at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:480)
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:399)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:350)
	at org.springframework.mail.javamail.JavaMailSender.send(JavaMailSender.java:101)
	...
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        ...
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/java.net.Socket.connect(Socket.java:583)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:335)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2160)
	... 47 more
```

From my test case, looking like so:

```kotlin
// send email by indirectly triggering the `JavaMailSender`

await().atMost(Duration.ofMinutes(2))
    .pollDelay(Duration.ofMillis(500))
    .until { greenMail?.receivedMessages?.isNotEmpty() }
```

I also get an exception:

```txt
java.lang.NullPointerException: Cannot invoke "com.icegreen.greenmail.util.GreenMail.getReceivedMessages()" because the return value of "com.icegreen.greenmail.util.GreenMailProxy.getGreenMail()" is null

	at com.icegreen.greenmail.util.GreenMailProxy.getReceivedMessages(GreenMailProxy.java:75)
	at io.axoniq.console.mail.MailServiceEventHandlerIntegrationTest.Handling_GracePeriodStarted_ends_early_for_missing_Handler_Limit_mail_properties$lambda$0(MailServiceEventHandlerIntegrationTest.kt:24)
	at org.awaitility.core.CallableCondition$ConditionEvaluationWrapper.eval(CallableCondition.java:99)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
```

As compared to the material I have found online (like the referred-to blogpost) to me looks identical to my approach, I am uncertain what I am doing wrong exactly.
Any help to  resolve this would be much appreciated!

**Comment by marcelmay** [comment]
It looks as if somehow GreenMail does not get initialized/started.  The NPE indicates that. As if the extension fails to register.  This should return true:
```java
greenMail.isRunning()
```

1. I created a similiar setup as a minimal [Spring Boot 3.2.x / GreenMail 2.1.0-alpha4 / Kotlin](https://github.com/greenmail-mail-test/greenmail-example-spring-boot-3/blob/spring-boot-3.2.x-kotlin/src/test/kotlin/com/greenmail/examples/springboot3/SpringBoot3ApplicationTests.kt)  example project.

2. Try to turn on GreenMail verbose logging

```java
    protected final val greenMail: GreenMailExtension = GreenMailExtension( ServerSetupTest.SMTP.verbose(true) )
        .withConfiguration(...
```

3. Debug into your test, e.g. set a breakpoint on com.icegreen.greenmail.util.GreenMail#start()

**Comment by smcvb** [comment]
Thanks for that, @marcelmay.
The crux happened to be the fact I **had not** added the `GreenMailExtension` in the `companion` block...after that, all worked fine.

With that, I think we can close this issue.
Thanks again for the support, @marcelmay :pray:
